# Generated by Django 5.0.7 on 2026-09-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(help_text="e.g. 'Building 6, Ground Floor'", max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before vendor can sell.')),
                ('is_open', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(default='08:00')),
                ('closes_at', models.TimeField(default='17:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_approved', 'is_open'], name='vendors_ven_is_appr_7974c5_idx')],
            },
        ),
    ]
