# Generated by Django 5.0.7 on 2026-09-18 11:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prep_time_minutes', models.PositiveSmallIntegerField(default=15)),
                ('category', models.CharField(choices=[('traditional', 'Traditional'), ('fast-food', 'Fast Food'), ('healthy', 'Healthy'), ('snacks', 'Snacks'), ('drinks', 'Drinks'), ('pizza', 'Pizza')], default='traditional', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='vendors.vendor')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['vendor', 'category', 'is_available'], name='menu_menuit_vendor__0692f6_idx')],
            },
        ),
    ]
